# Generated by Django 3.2.18 on 2023-04-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploadTask',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=300)),
                ('the_file', models.FileField(upload_to='')),
            ],
        ),
    ]
